src/main/java/com/sparta/moit/infra/InfraExam.java, src/main/resources/application.properties
=> Moitbe 29 dev/cicd

.github/workflows/feat.yml, src/main/java/com/sparta/moit/infra/InfraExam.java
* PR test (#12)
* Test: Jira Done Test MOITBE-29
* Test: Jira Done Test DONE MOITBE-29
* Test: Jira Done Test #done MOITBE-29
* Test: Jira Done Test #DONE MOITBE-29
* Test: Jira Done Test DONE MOITBE-29
* Test: Jira Done Test #DONE MOITBE-29
* DONE Test: Jira Done Test #DONE MOITBE-29
* Test: Jira Done Test #DONE MOITBE-29
* Test: Jira Done Test #DONE MOITBE-29
* Test: Jira Done Test
* Test: Jira Done Test MOITBE-29
* MOITBE-34 #done #comment Jira test
* MOITBE-34 #done #comment Jira test
* MOITBE-34 #done #comment Jira test
* MOITBE-34 #in-progress #comment Jira test
* Test: GithubAction CI/CD test
* Feat: CI/CD 환경 구축
Dockerfile추가
yml 추가
* Fix: branch 명 수정
* Fix: branch 명 수정
* Test: PR merge test
* Remove: cicd.yml 삭제
* Test: 지라 연결 branch cicd
* Test: 지라 연결 branch MOITBE
=> Moitbe 41 feat/cicd (#13)

src/main/java/com/sparta/moit/MoitApplication.java, src/main/java/com/sparta/moit/domain/member/service/KakaoService.java, src/main/java/com/sparta/moit/global/common/controller/CommonController.java, src/main/java/com/sparta/moit/global/common/dto/ResponseDto.java, src/main/java/com/sparta/moit/global/common/entity/Timestamped.java, src/main/java/com/sparta/moit/global/error/CustomException.java, src/main/java/com/sparta/moit/global/error/ErrorCode.java, src/main/java/com/sparta/moit/global/error/GlobalExceptionHandler.java
기존에 사용하던 방식으로 작성했으며,
다른 방법으로 리팩토링 진행할지 의견을 여쭙고 싶습니다 :)
=> feat: GlobalException 양식 추가

src/main/java/com/sparta/moit/infra/InfraExam.java
캐싱 적용 결과
통합 시간 단축: 약 50초 -> 약 25초
배포 시간 단축: 약 1분 30초 -> 40~50초
=> [Test] CI/CD caching CI test

src/main/java/com/sparta/moit/MoitApplication.java, src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java, src/main/java/com/sparta/moit/domain/meeting/dto/CreateMeetingRequestDto.java, src/main/java/com/sparta/moit/domain/meeting/dto/UpdateMeetingRequestDto.java, src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
=> feat: 모임 수정 기능 

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java, src/main/java/com/sparta/moit/domain/meeting/dto/CreateMeetingRequestDto.java, src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/entity/MeetingMember.java, src/main/java/com/sparta/moit/domain/meeting/entity/Meeting_Member.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingMemberRepository.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java, src/main/java/com/sparta/moit/domain/member/entity/Member.java, src/main/java/com/sparta/moit/domain/member/service/KakaoService.java, src/main/java/com/sparta/moit/global/error/ErrorCode.java, src/main/java/com/sparta/moit/global/security/UserDetailsServiceImpl.java
=> [FEAT] 모임 참가 기능

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
=> [FEAT] 모임 삭제 기능

src/main/java/com/sparta/moit/MoitApplication.java, src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java, src/main/java/com/sparta/moit/domain/meeting/dto/MeetingFilterCondition.java, src/main/java/com/sparta/moit/domain/meeting/dto/RegionSecondResponseDto.java, src/main/java/com/sparta/moit/domain/meeting/entity/RegionSecond.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java, src/main/java/com/sparta/moit/domain/meeting/repository/RegionSecondRepository.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java, src/main/java/com/sparta/moit/domain/meeting/service/RegionService.java, src/main/java/com/sparta/moit/domain/meeting/service/RegionServiceImpl.java, src/main/java/com/sparta/moit/global/common/controller/CommonController.java, src/main/java/com/sparta/moit/global/util/AddressUtil.java, src/test/java/com/sparta/moit/NaverServiceTest.java
- 반환 객체 Slice로 수정
- RegionSecond Entity lat, lng 추가
- NativeQuery 사용 중지
=> [Feat] QueryDsl Refactoring MOITBE-61

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java, src/main/java/com/sparta/moit/domain/meeting/dto/GetMeetingDetailResponseDto.java, src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java, src/main/java/com/sparta/moit/global/error/ErrorCode.java
=> [Feature] 모임 상세 조회 기능 구현

src/main/java/com/sparta/moit/MoitApplication.java, src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
- 검색 기준: keyword가 제목, 주소, 내용 중 하나라도 포함되어 있다면 catch
- 정렬 기준: 마감일 ASC / 참여인원 DESC
- Slice 페이징 처리: 무한 스크롤이 적용되는 것인지 확인 필요
=> [Feat] Search API 구현 MOITBE-70

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java, src/main/java/com/sparta/moit/domain/meeting/dto/GetMeetingDetailResponseDto.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
- 로그인 없이 모임 상세 조회 가능
- locationLng 정상 조회 수정
=> [Fix] 모임 상세 조회 hotfix

src/main/java/com/sparta/moit/domain/chat/controller/ChatController.java, src/main/java/com/sparta/moit/domain/chat/service/ChatService.java, src/main/java/com/sparta/moit/domain/chat/service/ChatServiceImpl.java, src/main/java/com/sparta/moit/global/config/StompHandler.java, src/main/java/com/sparta/moit/global/config/WebSocketConfig.java
=> [Feat] WebSocket interceptor 추가

src/main/java/com/sparta/moit/domain/chat/controller/ChatController.java, src/main/java/com/sparta/moit/domain/chat/service/ChatService.java, src/main/java/com/sparta/moit/domain/chat/service/ChatServiceImpl.java, src/main/java/com/sparta/moit/global/config/StompHandler.java, src/main/java/com/sparta/moit/global/security/UserDetailsImpl.java
- ChatController: @AuthenticationPrincipal -> Principal
- ChatService : User -> email 사용으로 변경
- StompHandler : StompHeaderAccessor.getAccessor(message, StompHeaderAccessor.class) , accessor.setUser(authentication) 으로 수정
- UserDetailsImpl : 'User' 하드코딩 -> authority 동적으로 변경
=> [Fix] StompHandler Auth 수정

src/main/java/com/sparta/moit/domain/meeting/dto/GetMeetingDetailResponseDto.java
=> [Fix] GetMeetingDetailResponseDto

src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
=> [FIX] 모임 탈퇴 기능

src/main/java/com/sparta/moit/domain/chat/dto/SenderResponseDto.java
=> [Fix] SenderResponseDto

src/main/java/com/sparta/moit/domain/chat/dto/SenderResponseDto.java
=> [Fix] SenderResponseDto memberEmail 필드 수정

src/main/java/com/sparta/moit/MoitApplication.java, src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/entity/MeetingStatusEnum.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java, src/main/java/com/sparta/moit/domain/member/entity/Member.java
=> [FIX]모임 삭제 기능

src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java, src/main/java/com/sparta/moit/domain/mypage/controller/MypageController.java, src/main/java/com/sparta/moit/domain/mypage/controller/MypageControllerDocs.java, src/main/java/com/sparta/moit/domain/mypage/dto/MypageMeetingResponseDto.java, src/main/java/com/sparta/moit/domain/mypage/service/MypageService.java, src/main/java/com/sparta/moit/domain/mypage/service/MypageServiceImpl.java
=> [Feat] 마이페이지 내가 참여한 모임 리스트 api 개발

src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
=> [FIX] 모임 상태 추가

src/main/java/com/sparta/moit/MoitApplication.java, src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java, src/main/java/com/sparta/moit/domain/meeting/scheduler/Scheduler.java
=> [FIX] 모임 상태 추가 

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java, src/main/java/com/sparta/moit/domain/meeting/dto/GetMeetingDetailResponseDto.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
- Controller에서 로그인 여부 분기 처리
- Service의 getMeetingDetail Override를 통해 로직 분리
- ResponseDto isJoin 필드 추가
=> [Feat] MeetingDetail 로그인 분기 + 참여 여부 로직 추가

src/main/java/com/sparta/moit/global/config/WebSecurityConfig.java, src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
- Add websocket connection url on WebSecurity URL permission lists
- Extend duration of JWT token from 10 sec-> 60 min
=> Moitbe 90 fix/chat exception

src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
- Revert token validity 60 min -> 10 second
=> [Fix] AccessToken 60분 -> 10초 유효 주기 변경

src/main/java/com/sparta/moit/domain/chat/controller/ChatController.java, src/main/java/com/sparta/moit/domain/chat/controller/docs/ChatControllerDocs.java, src/main/java/com/sparta/moit/domain/chat/dto/ChatResponseDto.java, src/main/java/com/sparta/moit/domain/chat/dto/SingleChatResponseDto.java, src/main/java/com/sparta/moit/domain/chat/repository/ChatRepository.java, src/main/java/com/sparta/moit/domain/chat/service/ChatService.java, src/main/java/com/sparta/moit/domain/chat/service/ChatServiceImpl.java
- Pageable 필드 추가
- 채팅 Id 기준으로 desc 정렬(채팅 최근 순)
- createdAt 필드 yyyy-MM-dd HH:mm 으로 형식 변경
=> [Feat] 무한 스크롤 api 구현

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
- /api/meetings/meetings/{meetingId} -> /api/meetings/{meetingId}
=> [Fix] 모임 상세 조회 url 수정

src/main/java/com/sparta/moit/MoitApplication.java, src/main/java/com/sparta/moit/domain/chat/controller/ChatController.java, src/main/java/com/sparta/moit/domain/chat/service/ChatServiceImpl.java, src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingMemberRepository.java, src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java, src/main/java/com/sparta/moit/domain/member/controller/MemberController.java, src/main/java/com/sparta/moit/domain/mypage/controller/MypageController.java, src/main/java/com/sparta/moit/domain/mypage/controller/docs/MypageControllerDocs.java, src/main/java/com/sparta/moit/domain/mypage/service/MypageServiceImpl.java, src/main/resources/application.properties
=> [FIX] 코드 리뷰 반영

src/main/java/com/sparta/moit/domain/mypage/dto/MypageMeetingResponseDto.java
- meetingDate, meetingStartTime, meetingEndTime 필드 추가
=> [Fix] 마이페이지 모임 리스트 시간관련 필드 추가

.gitignore, Dockerfile, build.gradle, src/main/java/com/sparta/moit/global/config/WebSecurityConfig.java, src/main/resources/application.properties
=> [ETC] Prometheus설정 

.github/workflows/deploy.yml, .github/workflows/dev.yml, .github/workflows/divide.yml, .github/workflows/docker.yml, Dockerfile, src/main/java/com/sparta/moit/global/common/controller/CommonController.java, src/main/resources/application.properties
- 서버 이사: EC2 단일서버 -> beanstalk
- ElastiCache
=> [Refactor] 무중단 배포 변경 Beanstalk

src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
=> [fix] KST 변환

src/main/java/com/sparta/moit/domain/meeting/dto/CreateMeetingRequestDto.java, src/main/java/com/sparta/moit/domain/member/controller/MemberController.java, src/main/java/com/sparta/moit/domain/member/controller/docs/MemberControllerDocs.java, src/main/java/com/sparta/moit/domain/member/service/KakaoServiceImpl.java, src/main/java/com/sparta/moit/domain/member/service/MemberService.java, src/main/java/com/sparta/moit/domain/member/service/MemberServiceImpl.java, src/main/java/com/sparta/moit/domain/member/service/NaverServiceImpl.java
=> fix] zoneDate -> LocalDateTime

src/main/java/com/sparta/moit/domain/meeting/controller/RegionController.java, src/main/java/com/sparta/moit/domain/meeting/dto/GetMeetingDetailResponseDto.java, src/main/java/com/sparta/moit/domain/meeting/dto/RegionIntegratedResponseDto.java, src/main/java/com/sparta/moit/domain/meeting/entity/RegionFirst.java, src/main/java/com/sparta/moit/domain/meeting/service/RegionService.java, src/main/java/com/sparta/moit/domain/meeting/service/RegionServiceImpl.java
- 1차 지역구, 2차 지역구 별도 API 구성 되었음
- 전체 조회로 변경되었음
=> Moitbe 112 fix/region

.github/workflows/docker.yml, Dockerfile, build.gradle, elasticbeanstalk/docker-compose.yml, src/main/java/com/sparta/moit/domain/bookmark/controller/BookMarkController.java, src/main/java/com/sparta/moit/domain/bookmark/controller/docs/BookMarkControllerDocs.java, src/main/java/com/sparta/moit/domain/bookmark/dto/GetBookMarkResponseDto.java, src/main/java/com/sparta/moit/domain/bookmark/repository/BookMarkRepository.java, src/main/java/com/sparta/moit/domain/member/repository/MemberRepository.java, src/main/resources/application.properties
- 유저가 북마크한 모임조회 API 생성
- 타임존 관련 코드 삭제
=> Moitbe 113 feat/api

src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java, src/main/java/com/sparta/moit/global/util/pagination/ListPaginator.java
- [해결]메인페이지 모임 검색시, 핀 안찍힘
- [해결]Query에 Complete 상태 제외 추가
=> Moitbe 115 fix/meeting

src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
=> [TEST] 테스트 로그인 에러

src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
=> [TEST] 테스트 로그인 에러 

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
- "/meetings/array" -> "/meetings" 로 변경
- "/meetings" -> "/meetings/json" 으로 변경
=> [Fix] array를 Meeting 변경

src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
=> [FIX] 토큰 시간 조정 

src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java, src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
=> [Fix] fix getSearchKeyword Dto

src/main/java/com/sparta/moit/global/common/controller/AuthController.java
- api/refresh/test 
- cookie refresh token 으로 access token 발급
=> [Fix] Test refresh access token with Cookie

src/main/java/com/sparta/moit/global/common/controller/AuthController.java, src/main/java/com/sparta/moit/global/common/service/RedisService.java, src/main/java/com/sparta/moit/global/common/service/RefreshTokenService.java
- refresh token 오류확인을 위한 로그 추가
=> [Fix] log token 추가

src/main/java/com/sparta/moit/global/common/controller/AuthController.java, src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
=> [Test] test log 추가 

.ebextensions/01_install_redis_cli.config
- added script to use redis-cli
- Checking redis connection with EC2 server
=> [Chore] add ebxtension to check redis conncection

src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
changes made for applicaton-dev
=> [Test] reload eb

src/main/java/com/sparta/moit/global/common/controller/AuthController.java, src/main/java/com/sparta/moit/global/common/controller/CommonController.java, src/main/java/com/sparta/moit/global/common/controller/docs/AuthControllerDocs.java, src/main/java/com/sparta/moit/global/common/service/RedisService.java, src/main/java/com/sparta/moit/global/common/service/RefreshTokenService.java, src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
- Fix refresh token 
- Removed unnecessary logs and methods
=> Fix refresh token

.github/workflows/gitActions_CD.yml
- github actions 배포 테스트용 trigger 추가
=> [FIX] add workflow_dispatch on workflow

.github/workflows/gitActions_CD.yml
=> [FIX] add workflow_dispatch on workflow (#178)

.github/workflows/gitActions_CD.yml, docker-compose.yml, src/main/resources/application-dev.properties
dev 브랜치를 main으로 병합하여 Let’s Encrypt SSL 인증서를 사용한 HTTPS 설정을 반영합니다.
- application.properties에서 HTTPS 설정 활성화.
- EC2 보안 그룹에 포트 443 인바운드 허용.
- 인증서 자동 갱신을 위한 cron 작업 설정.
=> [PR] Merge dev to main – HTTPS Configuration

docker-compose.yml, src/main/resources/application-dev.properties
=> [fix/backend-deploy] 서버 포트 명시

.github/workflows/gitActions_CD.yml, docker-compose.yml, src/main/resources/application-dev.properties
- Spring Application 8080-> 8443 변경
=> 8443 포트로 수정
